### PR TITLE
COntact page done,  i think

### PR DESCRIPTION
**Pull request by Mzwa1080**

### CODE REVIEW

**Review by zubairmoerat — APPROVED** [review]
Reviewed by Zubair

**Review by Anathi9 — COMMENTED** [review]
Reviewed by Anathi

**Review by Tarynleewalbrugh25 — APPROVED** [review]
reviewed by Taryn-lee

**Review by LuiV228 — APPROVED** [review]
Reviewed by Luqmaan

**Review by Anathi9 — APPROVED** [review]
Reviewed by Anathi

**Pull request merged**
